name: Backtest

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'   # toutes les 3 heures (évite rate limit)

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run backtests & generate report
        env:
          MPLBACKEND: Agg
        run: python auto_backtest.py
      - name: Commit report to /docs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto backtest: ${{ github.run_id }}"
          branch: ${{ github.ref_name }}
          file_pattern: docs/** outputs/**
